/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Farm {
  'id' : string,
  'created' : bigint,
  'productionCapacity' : number,
  'acreage' : number,
  'name' : string,
  'description' : string,
  'certifications' : Array<string>,
  'pondCount' : bigint,
  'species' : string,
}
export interface FarmPhoto {
  'id' : string,
  'order' : bigint,
  'caption' : string,
  'blobId' : Uint8Array,
  'farmId' : string,
}
export interface FarmerProfile {
  'about' : string,
  'name' : string,
  'contactEmail' : string,
  'location' : string,
  'contactPhone' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFarmPhoto' : ActorMethod<[FarmPhoto], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createFarm' : ActorMethod<[Farm], undefined>,
  'deleteFarm' : ActorMethod<[string], undefined>,
  'deleteFarmPhoto' : ActorMethod<[string], undefined>,
  'getAllFarms' : ActorMethod<[], Array<Farm>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFarmById' : ActorMethod<[string], [] | [Farm]>,
  'getFarmerProfile' : ActorMethod<[], [] | [FarmerProfile]>,
  'getPhotosByFarmId' : ActorMethod<[string], Array<FarmPhoto>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateFarm' : ActorMethod<[Farm], undefined>,
  'updateFarmPhoto' : ActorMethod<[FarmPhoto], undefined>,
  'updateFarmerProfile' : ActorMethod<[FarmerProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];